CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(150) NOT NULL,
                                     email VARCHAR(150) NOT NULL UNIQUE,
                                     CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(150) NOT NULL UNIQUE,
                                     CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS locations (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     lat VARCHAR(50) NOT NULL,
                                     lon VARCHAR(50) NOT NULL,
                                     CONSTRAINT pk_locations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     annotation VARCHAR(200),
                                     category BIGINT,
                                     description VARCHAR(500),
                                     event_date TIMESTAMP,
                                     location BIGINT,
                                     paid BOOLEAN,
                                     participant_limit BIGINT,
                                     request_moderation BOOLEAN,
                                     title VARCHAR(200),
                                     CONSTRAINT pk_events PRIMARY KEY (id),
                                     CONSTRAINT fk_events_to_category FOREIGN KEY(category) REFERENCES categories(id),
                                     CONSTRAINT fk_events_to_location FOREIGN KEY(location) REFERENCES locations(id)
);

CREATE TABLE IF NOT EXISTS compilations (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     pinned BOOLEAN NOT NULL,
                                     title VARCHAR(150) NOT NULL,
                                     CONSTRAINT pk_compilations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS eventsToCompilation (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     idCompilation BIGINT NOT NULL,
                                     idEvent BIGINT NOT NULL,
                                     CONSTRAINT pk_eventsToCompilation PRIMARY KEY (id),
                                     CONSTRAINT fk_eventsToCompilation_to_idCompilation FOREIGN KEY(idCompilation) REFERENCES compilations(id),
                                     CONSTRAINT fk_eventsToCompilation_to_idEvent FOREIGN KEY(idEvent) REFERENCES events(id)
);

CREATE TABLE IF NOT EXISTS requests (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     created TIMESTAMP NOT NULL,
                                     event BIGINT NOT NULL,
                                     requester BIGINT NOT NULL,
                                     status VARCHAR(50) NOT NULL,
                                     CONSTRAINT pk_requests PRIMARY KEY (id),
                                     CONSTRAINT fk_requests_to_event FOREIGN KEY(event) REFERENCES events(id),
                                     CONSTRAINT fk_requests_to_requester FOREIGN KEY(requester) REFERENCES requesters(id),
);