CREATE TABLE IF NOT EXISTS stats (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     app VARCHAR(200) NOT NULL,
                                     uri VARCHAR(100) NOT NULL,
                                     ip VARCHAR(30) NOT NULL,
                                     timestamp TIMESTAMP NOT NULL
);