CREATE TABLE IF NOT EXISTS stats (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     status VARCHAR(200) NOT NULL,
                                     status VARCHAR(100) NOT NULL,
                                     status VARCHAR(30) NOT NULL,
                                     status VARCHAR(30) NOT NULL
);